# Author: Cuong. Duong Manh
# Description: The configuration file to run the API service.
#              Put this file path in the argument `--config-file` when running the API service.

# The configuration parameters to run the API service
api_service:
  port: 8000       # The PORT to run the API service
  host: "0.0.0.0"  # The HOST to run the API service
  database:
    uri: "postgres://reforged-admin:reforged-admin-password@localhost:5432/reforged-api-service"