name: Package reforged-labs API service

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  package-image:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Login to VngCloud Registry
        uses: docker/login-action@v3
        continue-on-error: true
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build cluster-api-provider-vngcloud image
        shell: bash
        run: |
          export TAG=v0.0.0-$(date +'%y%m%d%H%M%S')
          export REGISTRY=${{ vars.DOCKER_REGISTRY }}
          make docker-build
          echo "VERSION=${TAG}" >> $GITHUB_ENV
      - name: Push cluster-api-provider-vngcloud image
        continue-on-error: true
        shell: bash
        run: |
          export TAG=$VERSION
          export REGISTRY=${{ vars.DOCKER_REGISTRY }}
          make docker-push
